# Generated by Django 4.2.7 on 2024-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0019_godown_godowncomments_godownhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='alter_gst_details',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cheque_book_range',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cheque_printing_configuration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='enable_cheque_printing',
            field=models.CharField(max_length=10),
        ),
    ]
